// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransactionService.Data;

#nullable disable

namespace TransactionService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230515225033_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TransactionService.Models.TransactionModel", b =>
                {
                    b.Property<Guid?>("TransactionExternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountExternalIdCredit")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountExternalIdDebit")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("TransactionStatusId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("TransactionTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("TransferTypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<decimal?>("Value")
                        .IsRequired()
                        .HasColumnType("numeric");

                    b.HasKey("TransactionExternalId");

                    b.HasIndex("TransactionStatusId");

                    b.HasIndex("TransactionTypeId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("TransactionService.Models.TransactionStatusModel", b =>
                {
                    b.Property<int>("TransactionStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionStatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("TransactionStatusId");

                    b.ToTable("TransactionStatus");

                    b.HasData(
                        new
                        {
                            TransactionStatusId = 1,
                            Name = "pending"
                        },
                        new
                        {
                            TransactionStatusId = 2,
                            Name = "approved"
                        },
                        new
                        {
                            TransactionStatusId = 3,
                            Name = "rejected"
                        });
                });

            modelBuilder.Entity("TransactionService.Models.TransactionTypeModel", b =>
                {
                    b.Property<int>("TransactionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("TransactionTypeId");

                    b.ToTable("TransactionType");

                    b.HasData(
                        new
                        {
                            TransactionTypeId = 1,
                            Name = "payment"
                        },
                        new
                        {
                            TransactionTypeId = 2,
                            Name = "credit"
                        });
                });

            modelBuilder.Entity("TransactionService.Models.TransactionModel", b =>
                {
                    b.HasOne("TransactionService.Models.TransactionStatusModel", "TransactionStatus")
                        .WithMany()
                        .HasForeignKey("TransactionStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransactionService.Models.TransactionTypeModel", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransactionStatus");

                    b.Navigation("TransactionType");
                });
#pragma warning restore 612, 618
        }
    }
}
